// Generated by https://quicktype.io

export interface CommentInterface {
    currentUser: User;
    comments:    Comment[];
}

export interface Comment {
    id:          number | string;
    content:     string;
    createdAt:   string;
    score:       number;
    user:        User;
    replies?:    Comment[];
    replyPostId?: number | string;
    replyingTo?: string;
}

export interface User {
    image:    Image;
    username: string;
}

export interface Image {
    png:  string;
    webp: string;
}


// Generated by https://quicktype.io

export interface Reply {
    id:          number;
    content:     string;
    createdAt:   string;
    score:       number;
    replyingTo:  string;
    replyPostId: number | string;
    user:        User;
}
